import type {
  ClinicalToolsResponse,
  DoseDrug,
  ScoringSystem,
  VitalsBand,
} from './clinical-tools.types';

const DOSE_DRUGS: DoseDrug[] = [
  {
    id: 'paracetamol',
    name: 'Paracetamol (oral)',
    indication: 'Fever / mild-to-moderate pain',
    mgPerKgPerDose: 15,
    maxMgPerDose: 1000,
    maxMgPerKgPerDay: 60,
    frequency: 'every 4–6 h',
    route: 'PO',
    notes: 'WHO / BNFc: 10–15 mg/kg/dose, max 4 doses in 24 h. Avoid in hepatic failure.',
  },
  {
    id: 'ibuprofen',
    name: 'Ibuprofen (oral)',
    indication: 'Fever / pain (>3 months)',
    mgPerKgPerDose: 10,
    maxMgPerDose: 400,
    maxMgPerKgPerDay: 40,
    frequency: 'every 6–8 h',
    route: 'PO',
    minAgeMonths: 3,
    notes:
      'BNFc: 5–10 mg/kg/dose; avoid in dehydration, asthma with sensitivity, renal impairment.',
  },
  {
    id: 'amoxicillin',
    name: 'Amoxicillin (oral)',
    indication: 'Community-acquired infection',
    mgPerKgPerDose: 25,
    maxMgPerDose: 500,
    maxMgPerKgPerDay: 90,
    frequency: 'every 8 h',
    route: 'PO',
    notes:
      'WHO IMCI / BNFc: standard 25 mg/kg/dose tds; up to 30 mg/kg/dose in severe pneumonia.',
  },
  {
    id: 'cotrimoxazole',
    name: 'Co-trimoxazole (oral)',
    indication: 'PCP / UTI / IMCI dysentery',
    mgPerKgPerDose: 4,
    maxMgPerDose: 160,
    frequency: 'every 12 h',
    route: 'PO',
    notes: 'Dose expressed as trimethoprim. Standard 4 mg/kg/dose bd.',
  },
  {
    id: 'zinc',
    name: 'Zinc sulphate',
    indication: 'Acute diarrhoea (IMCI)',
    mgPerKgPerDose: 20,
    maxMgPerDose: 20,
    frequency: 'once daily × 10–14 days',
    route: 'PO',
    notes: 'WHO IMCI: 20 mg daily ≥ 6 months; 10 mg daily 2–6 months.',
  },
  {
    id: 'ors',
    name: 'ORS (oral rehydration salts)',
    indication: 'Diarrhoea, mild dehydration (Plan A)',
    mgPerKgPerDose: 75,
    frequency: 'over 4 hours',
    route: 'PO',
    notes: 'Plan B: 75 mL/kg over 4 h. The calculator returns mL — not mg.',
  },
  {
    id: 'salbutamol',
    name: 'Salbutamol nebulised',
    indication: 'Acute wheeze / asthma',
    mgPerKgPerDose: 0.15,
    maxMgPerDose: 5,
    frequency: 'every 20 min × 3 then PRN',
    route: 'NEB',
    notes: 'BNFc: 0.15 mg/kg/dose (min 2.5 mg, max 5 mg).',
  },
  {
    id: 'prednisolone',
    name: 'Prednisolone (oral)',
    indication: 'Acute asthma / croup',
    mgPerKgPerDose: 1,
    maxMgPerDose: 40,
    maxMgPerKgPerDay: 2,
    frequency: 'once daily × 3 days',
    route: 'PO',
    notes: 'BNFc / GINA: 1–2 mg/kg once daily for short-course asthma exacerbation.',
  },
  {
    id: 'ceftriaxone',
    name: 'Ceftriaxone IV/IM',
    indication: 'Severe sepsis / meningitis',
    mgPerKgPerDose: 80,
    maxMgPerDose: 4000,
    frequency: 'once daily (bd for meningitis)',
    route: 'IV / IM',
    notes: 'Severe sepsis: 80–100 mg/kg/day. Meningitis: 100 mg/kg/day divided 12-hourly.',
  },
];

const VITALS: VitalsBand[] = [
  { band: 'Neonate (0–28 d)', hr: '120–160', rr: '30–60', sysBp: '60–80', spo2: '≥ 95' },
  { band: 'Infant (1–12 mo)', hr: '100–160', rr: '25–50', sysBp: '70–95', spo2: '≥ 95' },
  { band: 'Toddler (1–3 y)', hr: '90–150', rr: '20–40', sysBp: '80–100', spo2: '≥ 95' },
  { band: 'Pre-school (3–5 y)', hr: '80–140', rr: '20–30', sysBp: '85–105', spo2: '≥ 95' },
  { band: 'School (5–12 y)', hr: '70–120', rr: '16–25', sysBp: '90–115', spo2: '≥ 95' },
  { band: 'Adolescent (≥12 y)', hr: '60–100', rr: '12–20', sysBp: '100–130', spo2: '≥ 95' },
  { band: 'Adult', hr: '60–100', rr: '12–20', sysBp: '100–140', spo2: '≥ 95' },
];

const SCORING: ScoringSystem[] = [
  {
    id: 'news2',
    name: 'NEWS2',
    citation: 'Royal College of Physicians 2017. Adult inpatients (≥16y), not pregnant.',
    type: 'band',
    axes: [
      {
        id: 'rr',
        label: 'Respiratory rate (/min)',
        options: [
          { label: '≤ 8', score: 3 },
          { label: '9–11', score: 1 },
          { label: '12–20', score: 0 },
          { label: '21–24', score: 2 },
          { label: '≥ 25', score: 3 },
        ],
      },
      {
        id: 'spo2',
        label: 'SpO₂ scale 1 (%)',
        options: [
          { label: '≤ 91', score: 3 },
          { label: '92–93', score: 2 },
          { label: '94–95', score: 1 },
          { label: '≥ 96', score: 0 },
        ],
      },
      {
        id: 'air',
        label: 'Supplemental O₂',
        options: [
          { label: 'Air', score: 0 },
          { label: 'Oxygen', score: 2 },
        ],
      },
      {
        id: 'temp',
        label: 'Temperature (°C)',
        options: [
          { label: '≤ 35.0', score: 3 },
          { label: '35.1–36.0', score: 1 },
          { label: '36.1–38.0', score: 0 },
          { label: '38.1–39.0', score: 1 },
          { label: '≥ 39.1', score: 2 },
        ],
      },
      {
        id: 'sbp',
        label: 'Systolic BP (mmHg)',
        options: [
          { label: '≤ 90', score: 3 },
          { label: '91–100', score: 2 },
          { label: '101–110', score: 1 },
          { label: '111–219', score: 0 },
          { label: '≥ 220', score: 3 },
        ],
      },
      {
        id: 'hr',
        label: 'Heart rate (/min)',
        options: [
          { label: '≤ 40', score: 3 },
          { label: '41–50', score: 1 },
          { label: '51–90', score: 0 },
          { label: '91–110', score: 1 },
          { label: '111–130', score: 2 },
          { label: '≥ 131', score: 3 },
        ],
      },
      {
        id: 'avpu',
        label: 'Consciousness (ACVPU)',
        options: [
          { label: 'Alert', score: 0 },
          { label: 'New confusion', score: 3 },
          { label: 'V', score: 3 },
          { label: 'P', score: 3 },
          { label: 'U', score: 3 },
        ],
      },
    ],
  },
  {
    id: 'qsofa',
    name: 'qSOFA',
    citation: 'Singer JAMA 2016 / Sepsis-3. Outside ICU. ≥ 2 = increased mortality risk.',
    type: 'toggle',
    axes: [
      { id: 'resp', label: 'Respiratory rate ≥ 22/min', points: 1 },
      { id: 'sbp', label: 'Systolic BP ≤ 100 mmHg', points: 1 },
      { id: 'ams', label: 'Altered mental status (GCS < 15)', points: 1 },
    ],
  },
  {
    id: 'wells-pe',
    name: 'Wells PE',
    citation: 'Modified Wells (1998). Combine with age-adjusted D-dimer + CTPA per ESC 2019.',
    type: 'toggle',
    axes: [
      { id: 'dvt', label: 'Clinical signs/symptoms of DVT', points: 3 },
      { id: 'alt', label: 'PE is #1 diagnosis OR equally likely', points: 3 },
      { id: 'hr', label: 'Heart rate > 100/min', points: 1.5 },
      { id: 'immob', label: 'Immobilisation ≥ 3 d OR surgery in past 4 wk', points: 1.5 },
      { id: 'prior', label: 'Previous DVT/PE', points: 1.5 },
      { id: 'haemo', label: 'Haemoptysis', points: 1 },
      { id: 'malig', label: 'Malignancy (treatment in 6 mo or palliative)', points: 1 },
    ],
  },
  {
    id: 'cha2ds2-vasc',
    name: 'CHA₂DS₂-VASc',
    citation: 'ESC 2024 + ACC/AHA/HRS 2023. Non-valvular AF stroke risk.',
    type: 'toggle',
    axes: [
      { id: 'chf', label: 'Congestive heart failure / LV dysfunction', points: 1 },
      { id: 'htn', label: 'Hypertension', points: 1 },
      { id: 'age75', label: 'Age ≥ 75', points: 2 },
      { id: 'dm', label: 'Diabetes mellitus', points: 1 },
      { id: 'stroke', label: 'Prior stroke / TIA / thromboembolism', points: 2 },
      { id: 'vasc', label: 'Vascular disease (MI / PAD / aortic plaque)', points: 1 },
      { id: 'age65', label: 'Age 65–74', points: 1 },
      { id: 'sex', label: 'Sex category female', points: 1 },
    ],
  },
];

export const CLINICAL_TOOLS_DATA: ClinicalToolsResponse = {
  doseDrugs: DOSE_DRUGS,
  vitals: VITALS,
  scoringSystems: SCORING,
};
