/**
 * Word-level tools for the chat grounding gate. Question and records are
 * tokenised the same way, so "infections" in a question meets "infection" in a
 * record.
 */

/**
 * Words that carry no evidence that a record answers a question: question
 * scaffolding, and clinical vocabulary common enough to appear in thousands
 * of records ("dose", "treatment", "child"). Stored in folded form.
 */
const STOP_WORDS = new Set(
  [
    // scaffolding
    'what',
    'when',
    'which',
    'where',
    'who',
    'why',
    'how',
    'does',
    'did',
    'should',
    'would',
    'could',
    'can',
    'will',
    'may',
    'might',
    'must',
    'shall',
    'give',
    'giving',
    'given',
    'take',
    'taking',
    'use',
    'used',
    'using',
    'about',
    'there',
    'this',
    'that',
    'these',
    'those',
    'with',
    'without',
    'from',
    'into',
    'have',
    'has',
    'had',
    'need',
    'needs',
    'much',
    'many',
    'the',
    'for',
    'and',
    'are',
    'was',
    'were',
    'you',
    'your',
    'per',
    'any',
    'all',
    'some',
    'other',
    'than',
    'then',
    'also',
    'just',
    'only',
    'very',
    'more',
    'most',
    'less',
    'least',
    'enough',
    'right',
    'okay',
    'fine',
    'tell',
    'know',
    'please',
    'want',
    'like',
    'get',
    'got',
    'make',
    'our',
    'its',
    'not',
    'yes',
    'but',
    'too',
    'still',
    'again',
    'after',
    'before',
    'during',
    'while',
    'between',
    'over',
    'under',
    'same',
    'each',
    'both',
    'either',
    'such',
    'is',
    'it',
    'in',
    'of',
    'to',
    'on',
    'at',
    'an',
    'as',
    'be',
    'by',
    'do',
    'if',
    'me',
    'my',
    'no',
    'or',
    'so',
    'up',
    'we',
    'am',
    'he',
    'she',
    'his',
    'her',
    'him',
    'they',
    'them',
    // generic clinical vocabulary
    'dose',
    'doses',
    'dosing',
    'dosage',
    'dosages',
    'adult',
    'adults',
    'child',
    'children',
    'kid',
    'kids',
    'paediatric',
    'pediatric',
    'infant',
    'infants',
    'neonate',
    'neonates',
    'baby',
    'babies',
    'patient',
    'patients',
    'person',
    'woman',
    'women',
    'man',
    'men',
    'mother',
    'treatment',
    'treatments',
    'treat',
    'treating',
    'therapy',
    'management',
    'manage',
    'managing',
    'range',
    'level',
    'levels',
    'safe',
    'safety',
    'best',
    'first',
    'second',
    'third',
    'line',
    'choice',
    'drug',
    'drugs',
    'medicine',
    'medicines',
    'medication',
    'medications',
    'tablet',
    'tablets',
    'daily',
    'regimen',
    'regimens',
    'contraindicated',
    'contraindication',
    'contraindications',
    'interact',
    'interacts',
    'interaction',
    'interactions',
    'combine',
    'combined',
    'combination',
    'titrate',
    'titration',
    'threshold',
    'maximum',
    'max',
    'minimum',
    'min',
    'loading',
    'maintenance',
    'prescribe',
    'prescribing',
    'prescription',
    'therapeutic',
    'recommended',
    'preferred',
    'often',
    'long',
    'frequency',
    'duration',
    'acute',
    'chronic',
    'severe',
    'mild',
    'moderate',
    'uncomplicated',
    'complicated',
    'disease',
    'syndrome',
    'condition',
    'old',
    'aged',
    'age',
    'female',
    'male',
    'weight',
    'weighing',
    'weighs',
    'weigh',
    'kilo',
    'kilos',
    'kilogram',
    'kilograms',
    'normal',
    'usual',
    'standard',
    'common',
    'cause',
    'causes',
    'sign',
    'signs',
    'symptom',
    'symptoms',
    // Swahili scaffolding
    'kipimo',
    'dozi',
    'dawa',
    'gani',
    'mara',
    'ngapi',
    'siku',
    'kwa',
    'cha',
    'ya',
    'na',
    'je',
    'ni',
    'za',
    'wa',
    'la',
    'mtoto',
    'watoto',
    'kilo',
    'salama',
    'kutumia',
    'nimpe',
    'mpe',
    'zipi',
    'nini',
    'vipi',
  ].map(foldPlural),
);

const UNIT_WORDS = new Set([
  'mg',
  'mcg',
  'ug',
  'g',
  'kg',
  'ml',
  'l',
  'iu',
  'unit',
  'mmol',
  'meq',
  'hour',
  'hr',
  'day',
  'week',
  'month',
  'year',
  'yr',
  'y',
  'mo',
  'min',
  'minute',
  'time',
]);

/** Singular form used on both sides of every comparison. */
export function foldPlural(t: string): string {
  if (t.length > 4 && t.endsWith('ies')) return `${t.slice(0, -3)}y`;
  if (t.length > 3 && t.endsWith('s') && !/(ss|us|is)$/.test(t)) return t.slice(0, -1);
  return t;
}

export function tokenize(text: string): string[] {
  return text
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter(Boolean)
    .map(foldPlural);
}

/** "500mg", "14kg", "2", "hours" — quantities, not subjects. */
export function isNumericOrUnit(t: string): boolean {
  return /^\d/.test(t) || UNIT_WORDS.has(t);
}

export function isStopWord(t: string): boolean {
  return STOP_WORDS.has(t);
}

/** Question words that could name what the question is about. */
export function candidateTerms(question: string): string[] {
  return [
    ...new Set(
      tokenize(question).filter((t) => t.length >= 2 && !isStopWord(t) && !isNumericOrUnit(t)),
    ),
  ];
}
